apiVersion: v1
kind: ServiceAccount
metadata:
  name: drc-io-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drc-io-agent
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drc-io-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drc-io-agent
subjects:
- kind: ServiceAccount
  name: drc-io-agent
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drc-io-agent
  namespace: default
  labels:
    app: drc-io-agent
spec:
  selector:
    matchLabels:
      app: drc-io-agent
  template:
    metadata:
      labels:
        app: drc-io-agent
    spec:
      serviceAccountName: drc-io-agent
      hostPID: true
      securityContext:
        privileged: true
      containers:
      - name: drc-io-agent
        image: drc-io-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POLL_INTERVAL
          value: "5"
        - name: SHARED_MOUNT_PATH
          value: "/mnt/features"
        - name: READ_BANDWIDTH_LIMIT
          value: "200M"
        - name: WRITE_BANDWIDTH_LIMIT
          value: "50M"
        - name: METRICS_PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: false
        - name: features
          mountPath: /mnt/features
          readOnly: false
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: features
        hostPath:
          path: /mnt/features
          type: DirectoryOrCreate

